import { Injectable } from '@angular/core';
import { GroceriesServiceService } from './groceries-service.service';
import { AlertController } from '@ionic/angular';

@Injectable({
  providedIn: 'root'
})
export class InputDialogService {

  constructor(public dataService: GroceriesServiceService, public alertController: AlertController) { }

  async showPrompt(item?, index?) {
    const alert = await this.alertController.create({
      header: item ? 'Edit Item' : 'Add Item',
      message: item ? 'Please edit this item...' : 'Please enter an item...',
      inputs: [
        {
          name: 'name',
          type: 'text',
          placeholder: 'Name',
          value: item ? item.name : null,
        },
        {
          name: 'quantity',
          type: 'text',
          placeholder: 'Quantity',
          value: item ? item.quantity : null,
        },
        {
          name: 'id',
          type: 'text',
          disabled: true,
          placeholder: 'Id (Autogenerated)',
          value: item ? item._id : null
        }
      ],
      buttons: [
        {
          text: 'Cancel',
          handler: () => {
            console.log('Confirm Cancel')
          }
        },
        {
          text: 'Save',
          handler: (item) => {
            console.log('Confirm Save', item);
            if (index !== undefined) {
              this.dataService.editItem(item, index);
            }
            else {
              this.dataService.addItem(item);
            }
          }
        }
      ]
    });
    await alert.present();
  }
}
